### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by abcussi**
pull submission request to the first review.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires few changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!

Here just a few changes, before this project can e approved:

* [ ] Project should have a share button, right now it's just a `div` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
* [ ]  It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Project Approved :100: 
### You have done a great job with this project. 
image


##### Go ahead and merge to master. 
##### Good luck in your next project Happy coding

**Review by Forison — APPROVED** [review]
## Hi team,
## Your project has already been approved by the previous TSE so go ahead and merge and move to the next project.

**Pull request merged**
